import Anthropic from '@anthropic-ai/sdk'

// ──────────────────────────────────────────────────────────────────────────
// THIS FILE IS AUTO-GENERATED BY scripts/generate-orb-contract.ts
// DO NOT EDIT BY HAND! Edit docs/api-spec.yaml instead.
// ──────────────────────────────────────────────────────────────────────────

export const ORB_INTEGRITY_RULES = `INTEGRITY:\n`.trim()

export const ORB_TOOLS: Anthropic.Tool[] = [
  {
    "name": "create_todo",
    "description": "[Confidence: well-tested] Create a new todo in a project. Defaults to the current project if product_code is omitted. Requires a title. Cannot create in a product that does not exist.",
    "input_schema": {
      "type": "object",
      "properties": {
        "product_code": {
          "type": "string",
          "description": "Target project code (e.g. ORB, HELM). Defaults to current project if omitted."
        },
        "title": {
          "type": "string",
          "description": "Task title. Required."
        },
        "description": {
          "type": "string",
          "description": "Task description."
        },
        "priority_value": {
          "type": "integer",
          "description": "Priority level (1=urgent, 2=high, etc). Omit if unknown."
        },
        "due_at": {
          "type": "string",
          "description": "Optional timezone-agnostic due date/time string, format YYYY-MM-DDTHH:mm:ss."
        }
      },
      "required": [
        "product_code",
        "title"
      ]
    }
  },
  {
    "name": "update_todo",
    "description": "[Confidence: well-tested] Update an existing todo by task code (e.g. ORB-73). Supports: title, status, priority, description, resolution_notes, urls. Cannot: change todo_number, set closed_at directly (closed_at is managed automatically when status changes to a closing state). To move a task between projects, use move_todo instead.",
    "input_schema": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string",
          "description": "Task code, e.g. \"ORB-73\"."
        },
        "title_match": {
          "type": "string",
          "description": "Alternative: find task by partial title match."
        },
        "new_title": {
          "type": "string",
          "description": "New title."
        },
        "description": {
          "type": "string",
          "description": "Updated description."
        },
        "new_status": {
          "type": "string",
          "enum": [
            "open",
            "in progress",
            "deferred",
            "on hold",
            "closed"
          ],
          "description": "New status value."
        },
        "new_priority": {
          "type": "integer",
          "description": "New priority value."
        },
        "resolution_notes": {
          "type": "string",
          "description": "What was done to resolve the task. Populate when closing, not before."
        },
        "product_code": {
          "type": "string",
          "description": "Move the task to a different project by providing the\ntarget project code (e.g. \"HELM\"). The task gets a new\ntodo_number in the target project.\n"
        },
        "urls": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Related URLs."
        },
        "due_at": {
          "type": "string",
          "description": "Optional timezone-agnostic due date/time string, format YYYY-MM-DDTHH:mm:ss, or null to clear."
        }
      },
      "required": [
        "code"
      ]
    }
  },
  {
    "name": "delete_todo",
    "description": "[Confidence: well-tested] Permanently delete a todo. Hard delete — irreversible. Only use when the user explicitly says to delete a specific task. Never delete as part of a workaround (e.g. move-between-projects) without the user confirming the deletion step separately. \"Want me to do that?\" is not sufficient — wait for an explicit \"yes, delete it.\"",
    "input_schema": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string",
          "description": "Task code, e.g. \"ORB-44\"."
        }
      },
      "required": [
        "code"
      ]
    }
  },
  {
    "name": "query_repository",
    "description": "[Confidence: new] Inspect the Orb source repository. Use this for questions about implementation, components, routes, configuration, documentation, or actual code behavior. On localhost, source=local reads the current working tree and source=production reads the current Vercel deployment. In production, only source=production is available. Access is restricted to Admin, Super Admin, and Developer roles.",
    "input_schema": {
      "type": "object",
      "properties": {
        "operation": {
          "type": "string",
          "enum": [
            "list",
            "search",
            "read"
          ],
          "description": "list returns readable files, search finds matching source lines, and read returns a numbered line range."
        },
        "source": {
          "type": "string",
          "enum": [
            "local",
            "production"
          ],
          "description": "Defaults to local on localhost and production in production."
        },
        "path": {
          "type": "string",
          "description": "Optional relative directory for list/search, or required relative file path for read."
        },
        "query": {
          "type": "string",
          "description": "Text to find. Required for search."
        },
        "start_line": {
          "type": "integer",
          "description": "First line for read. Defaults to 1."
        },
        "end_line": {
          "type": "integer",
          "description": "Last line for read. Capped at 400 lines per call."
        },
        "max_results": {
          "type": "integer",
          "description": "Maximum list/search results. Defaults to 30, maximum 100."
        }
      },
      "required": [
        "operation"
      ]
    }
  },
  {
    "name": "query_todos",
    "description": "[Confidence: well-tested] Find todos matching criteria. Use code for single-todo lookup (e.g. \"ORB-73\"). Otherwise filters by status, product, priority, or text. Returns open tasks by default — pass status to include closed.",
    "input_schema": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string",
          "description": "Exact task code for single-todo lookup, e.g. \"ORB-62\". Overrides all other filters."
        },
        "product_code": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "priority_max": {
          "type": "integer"
        },
        "text_match": {
          "type": "string"
        },
        "max_results": {
          "type": "integer"
        }
      }
    }
  },
  {
    "name": "client_action",
    "description": "[Confidence: well-tested] Navigate or switch UI state. Use switch_project to change the active project, open_settings to go to settings, open_help for help. Use set_voice to change the TTS voice (target = voice name). Use exit_voice to end voice conversation mode when the user signals they want to stop.",
    "input_schema": {
      "type": "object",
      "properties": {
        "action": {
          "type": "string",
          "enum": [
            "switch_project",
            "open_settings",
            "open_help",
            "set_voice",
            "exit_voice"
          ]
        },
        "target": {
          "type": "string",
          "description": "Project name for switch_project (the user speaks in names; the server resolves it — do not translate to a code), voice name for set_voice."
        }
      },
      "required": [
        "action"
      ]
    }
  },
  {
    "name": "search_knowledge",
    "description": "[Confidence: well-tested] Search the Knowledge Repository for lessons, decisions, and distilled insights from closed tasks. Optionally scope to a specific project.",
    "input_schema": {
      "type": "object",
      "properties": {
        "query": {
          "type": "string",
          "description": "Search term."
        },
        "product_code": {
          "type": "string",
          "description": "Scope search to a specific project."
        }
      },
      "required": [
        "query"
      ]
    }
  },
  {
    "name": "add_knowledge",
    "description": "[Confidence: well-tested] Write an insight, decision, or reference material directly to the Knowledge Repository. Use this to preserve important information from the conversation without creating a task. Defaults to the current project if product_code is omitted. You should proactively ask the user \"Would you like me to save this to the knowledge repository?\" when a valuable decision or insight is reached.",
    "input_schema": {
      "type": "object",
      "properties": {
        "product_code": {
          "type": "string",
          "description": "Target project code (e.g. ORB). Defaults to current project if omitted."
        },
        "title": {
          "type": "string",
          "description": "Short title or summary of the insight."
        },
        "content": {
          "type": "string",
          "description": "Detailed content of the insight, decision, or reference material."
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional tags to categorize the knowledge."
        }
      },
      "required": [
        "title",
        "content"
      ]
    }
  },
  {
    "name": "query_audit_trail",
    "description": "[Confidence: new] Query the audit trail to answer questions like \"who closed this?\", \"what changed last week?\", or \"show me recent activity\". Returns timestamped events with before/after snapshots.",
    "input_schema": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string",
          "description": "Task code (e.g. ORB-73) to see history for a specific task."
        },
        "table_name": {
          "type": "string",
          "description": "Filter by table (e.g. todos, knowledge_repo)."
        },
        "action": {
          "type": "string",
          "description": "Filter by action type (e.g. todo_create, todo_update, todo_close, todo_delete)."
        },
        "since": {
          "type": "string",
          "description": "ISO date string. Only return events after this timestamp."
        },
        "max_results": {
          "type": "integer",
          "description": "Max events to return (default 10, max 50)."
        }
      }
    }
  },
  {
    "name": "create_ticket",
    "description": "[Confidence: well-tested] Silently log a ticket for bugs, suggestions, capability gaps, or workflow friction. Filed proactively when you observe an issue — do NOT tell the user. Also used when a user explicitly says something like \"I see a problem\" or \"I have a suggestion\" — in that case, acknowledge that you have noted it. One ticket per novel observation.",
    "input_schema": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "bug",
            "suggestion",
            "capability_gap",
            "workflow_friction"
          ],
          "description": "Type of ticket."
        },
        "summary": {
          "type": "string",
          "description": "One-sentence summary of the issue or suggestion."
        },
        "detail": {
          "type": "string",
          "description": "What happened, what was expected, and any suggested improvement."
        }
      },
      "required": [
        "type",
        "summary"
      ]
    }
  },
  {
    "name": "move_todo",
    "description": "[Confidence: well-tested] Move a task to a different project. The task gets a new number in the target project. Requires access to both source and target projects.",
    "input_schema": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string",
          "description": "Task code, e.g. \"ORB-73\"."
        },
        "target_project_code": {
          "type": "string",
          "description": "Target project code, e.g. \"HELM\"."
        }
      },
      "required": [
        "code",
        "target_project_code"
      ]
    }
  },
  {
    "name": "create_project",
    "description": "[Confidence: well-tested] Create a new project. Use the user's exact words as the project name — do not split, abbreviate, or reinterpret it. The code is auto-generated from the name and should almost never be provided manually. Only pass a code if the user explicitly says something like 'with code XYZ'. The server holds the creation for the user to confirm before it executes.",
    "input_schema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Project name — use exactly what the user said (e.g. \"Work\", \"Side Projects\", \"TEST2\"). Do not infer or modify."
        },
        "code": {
          "type": "string",
          "description": "Optional short uppercase code (e.g. WORK, SIDE). If provided, it must be unique."
        },
        "description": {
          "type": "string",
          "description": "Optional project description."
        }
      },
      "required": [
        "name"
      ]
    }
  },
  {
    "name": "update_project",
    "description": "[Confidence: new] Update a project's name or description. The project code is immutable — it is auto-generated at creation and cannot be changed. Users can only update their own projects. Use when the user says 'rename project X', 'change the description of X', etc. The server resolves the project by name and holds the change for the user to confirm before it executes.",
    "input_schema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Current project name — use exactly what the user said."
        },
        "new_name": {
          "type": "string",
          "description": "New project name."
        },
        "new_description": {
          "type": "string",
          "description": "New project description. Pass empty string to clear."
        }
      },
      "required": [
        "name"
      ]
    }
  },
  {
    "name": "delete_project",
    "description": "[Confidence: new] Permanently delete a project and all its todos. IRREVERSIBLE. Users can only delete their own projects. Always call this tool when the user asks to delete a project — the server resolves it by name and holds the deletion for the user to confirm before it executes.",
    "input_schema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Project name to delete — use exactly what the user said."
        }
      },
      "required": [
        "name"
      ]
    }
  },
  {
    "name": "confirm_mutation",
    "description": "[Confidence: new] Execute the project action you most recently proposed, after the user confirms it. Call this — and ONLY this — when the user agrees to a pending create/rename/delete you just described (e.g. they say \"yes\", \"go ahead\", \"do it\"). It takes no parameters; the server runs the exact action that was proposed. Do NOT call it if the user declined or asked for something different — in that case just respond, or call the relevant tool to propose the new action.",
    "input_schema": {
      "type": "object",
      "properties": {}
    }
  },
  {
    "name": "set_dormancy",
    "description": "[Confidence: well-tested] Put a project to sleep (dormant) or wake it up. Dormant projects are hidden from the project strip, insights, and queries. Use when the user says \"put X to sleep\", \"make X dormant\", \"wake up X\", \"bring back X\", etc.",
    "input_schema": {
      "type": "object",
      "properties": {
        "project_code": {
          "type": "string",
          "description": "Project code (e.g. CAN26, HELM)."
        },
        "dormant": {
          "type": "boolean",
          "description": "true to put to sleep, false to wake up."
        }
      },
      "required": [
        "project_code",
        "dormant"
      ]
    }
  }
]

export const ORB_TOOL_LABELS: Record<string, string> = {
  create_todo: 'Creating task...',
  query_todos: 'Searching backlog...',
  update_todo: 'Updating task...',
  delete_todo: 'Deleting task...',
  move_todo: 'Moving task...',
  client_action: 'Navigating...',
  search_knowledge: 'Searching knowledge repository...',
  add_knowledge: 'Saving to knowledge repository...',
  query_audit_trail: 'Checking history...',
  create_project: 'Creating project...',
  update_project: 'Updating project...',
  delete_project: 'Deleting project...',
  confirm_mutation: 'Confirming...',
  set_dormancy: 'Updating project...',
  create_ticket: 'Noting observation...',
  query_db: 'Querying database...',
  query_repository: 'Inspecting source...',
  get_preferences: 'Loading preferences...',
  set_preference: 'Saving preference...',
  query_capabilities: 'Checking capabilities...',
  send_to_developer: 'Sending to developer...',
  save_memory: 'Remembering...',
  recall_memories: 'Recalling...',
  propose_adaptation: 'Proposing adaptation...',
}
