import Anthropic from '@anthropic-ai/sdk'

// ──────────────────────────────────────────────────────────────────────────
// THIS FILE IS AUTO-GENERATED BY scripts/generate-orb-contract.ts
// DO NOT EDIT BY HAND! Edit docs/api-spec.yaml instead.
// ──────────────────────────────────────────────────────────────────────────

export const ORB_INTEGRITY_RULES = `INTEGRITY:\n`.trim()

export const ORB_TOOLS: Anthropic.Tool[] = [
  {
    "name": "create_todo",
    "description": "[Confidence: well-tested] Create a new todo in a project. Defaults to the current project if product_code is omitted. Requires a title. Cannot create in a product that does not exist.",
    "input_schema": {
      "type": "object",
      "properties": {
        "product_code": {
          "type": "string",
          "description": "Target project code (e.g. ORB, HELM). Defaults to current project if omitted."
        },
        "title": {
          "type": "string",
          "description": "Task title. Required."
        },
        "description": {
          "type": "string",
          "description": "Task description."
        },
        "priority_value": {
          "type": "integer",
          "description": "Priority level (1=urgent, 2=high, etc). Omit if unknown."
        },
        "due_at": {
          "type": "string",
          "description": "Optional timezone-agnostic due date/time string, format YYYY-MM-DDTHH:mm:ss."
        }
      },
      "required": [
        "product_code",
        "title"
      ]
    }
  },
  {
    "name": "update_todo",
    "description": "[Confidence: well-tested] Update an existing todo by task code (e.g. ORB-73). Supports: title, status, priority, description, resolution_notes, urls. Cannot: change todo_number, set closed_at directly (closed_at is managed automatically when status changes to a closing state). To move a task between projects, use move_todo instead.",
    "input_schema": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string",
          "description": "Task code, e.g. \"ORB-73\"."
        },
        "title_match": {
          "type": "string",
          "description": "Alternative: find task by partial title match."
        },
        "new_title": {
          "type": "string",
          "description": "New title."
        },
        "description": {
          "type": "string",
          "description": "Updated description."
        },
        "new_status": {
          "type": "string",
          "enum": [
            "open",
            "in progress",
            "deferred",
            "on hold",
            "closed"
          ],
          "description": "New status value."
        },
        "new_priority": {
          "type": "integer",
          "description": "New priority value."
        },
        "resolution_notes": {
          "type": "string",
          "description": "What was done to resolve the task. Populate when closing, not before."
        },
        "product_code": {
          "type": "string",
          "description": "Move the task to a different project by providing the\ntarget project code (e.g. \"HELM\"). The task gets a new\ntodo_number in the target project.\n"
        },
        "urls": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Related URLs."
        },
        "due_at": {
          "type": "string",
          "description": "Optional timezone-agnostic due date/time string, format YYYY-MM-DDTHH:mm:ss, or null to clear."
        }
      },
      "required": [
        "code"
      ]
    }
  },
  {
    "name": "delete_todo",
    "description": "[Confidence: well-tested] Permanently delete a todo. Hard delete — irreversible. Only use when the user explicitly says to delete a specific task. Never delete as part of a workaround (e.g. move-between-projects) without the user confirming the deletion step separately. \"Want me to do that?\" is not sufficient — wait for an explicit \"yes, delete it.\"",
    "input_schema": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string",
          "description": "Task code, e.g. \"ORB-44\"."
        }
      },
      "required": [
        "code"
      ]
    }
  },
  {
    "name": "query_todos",
    "description": "[Confidence: well-tested] Find todos matching criteria. Use code for single-todo lookup (e.g. \"ORB-73\"). Otherwise filters by status, product, priority, or text. Returns ALL statuses by default. Use status_group='active' or status_group='parked' to narrow. Each result includes the task owner's name.",
    "input_schema": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string",
          "description": "Exact task code for single-todo lookup, e.g. \"ORB-62\". Overrides all other filters."
        },
        "product_code": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "priority_max": {
          "type": "integer"
        },
        "text_match": {
          "type": "string"
        },
        "max_results": {
          "type": "integer"
        }
      }
    }
  },
  {
    "name": "client_action",
    "description": "[Confidence: well-tested] Navigate, switch UI state, or trigger client-side actions. Actions: switch_project (change active project), open_settings, open_help, check_update (check if a newer version is available — ONLY when the user explicitly asks, never proactively), apply_update (reload the app to pick up a new version — ONLY after the user gives permission or their request implies it, e.g. 'update the app if one is available'). The app already has automatic update detection — these actions are for user-initiated checks only.",
    "input_schema": {
      "type": "object",
      "properties": {
        "action": {
          "type": "string",
          "enum": [
            "switch_project",
            "open_settings",
            "open_help",
            "check_update",
            "apply_update"
          ]
        },
        "target": {
          "type": "string",
          "description": "Project code for switch_project."
        }
      },
      "required": [
        "action"
      ]
    }
  },
  {
    "name": "search_knowledge",
    "description": "[Confidence: well-tested] Search the Knowledge Repository for lessons, decisions, and distilled insights from closed tasks. Optionally scope to a specific project.",
    "input_schema": {
      "type": "object",
      "properties": {
        "query": {
          "type": "string",
          "description": "Search term."
        },
        "product_code": {
          "type": "string",
          "description": "Scope search to a specific project."
        }
      },
      "required": [
        "query"
      ]
    }
  },
  {
    "name": "add_knowledge",
    "description": "[Confidence: well-tested] Write an insight, decision, or reference material directly to the Knowledge Repository. Use this to preserve important information from the conversation without creating a task. Defaults to the current project if product_code is omitted. You should proactively ask the user \"Would you like me to save this to the knowledge repository?\" when a valuable decision or insight is reached.",
    "input_schema": {
      "type": "object",
      "properties": {
        "product_code": {
          "type": "string",
          "description": "Target project code (e.g. ORB). Defaults to current project if omitted."
        },
        "title": {
          "type": "string",
          "description": "Short title or summary of the insight."
        },
        "content": {
          "type": "string",
          "description": "Detailed content of the insight, decision, or reference material."
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional tags to categorize the knowledge."
        }
      },
      "required": [
        "title",
        "content"
      ]
    }
  },
  {
    "name": "query_audit_trail",
    "description": "[Confidence: new] Query the audit trail to answer questions like \"who closed this?\", \"what changed last week?\", or \"show me recent activity\". Returns timestamped events with before/after snapshots.",
    "input_schema": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string",
          "description": "Task code (e.g. ORB-73) to see history for a specific task."
        },
        "table_name": {
          "type": "string",
          "description": "Filter by table (e.g. todos, knowledge_repo)."
        },
        "action": {
          "type": "string",
          "description": "Filter by action type (e.g. todo_create, todo_update, todo_close, todo_delete)."
        },
        "since": {
          "type": "string",
          "description": "ISO date string. Only return events after this timestamp."
        },
        "max_results": {
          "type": "integer",
          "description": "Max events to return (default 10, max 50)."
        }
      }
    }
  },
  {
    "name": "create_ticket",
    "description": "[Confidence: well-tested] Silently log feedback (bugs, suggestions, capability gaps, or workflow friction) as a todo in the Tickets project. Filed proactively when you observe an issue — do NOT tell the user. Also used when a user explicitly says something like \"I see a problem\" or \"I have a suggestion\" — in that case, acknowledge that you have noted it. One entry per novel observation.",
    "input_schema": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "bug",
            "suggestion",
            "capability_gap",
            "workflow_friction"
          ],
          "description": "Type of feedback."
        },
        "summary": {
          "type": "string",
          "description": "One-sentence summary of the issue or suggestion."
        },
        "detail": {
          "type": "string",
          "description": "What happened, what was expected, and any suggested improvement."
        }
      },
      "required": [
        "type",
        "summary"
      ]
    }
  },
  {
    "name": "move_todo",
    "description": "[Confidence: well-tested] Move a task to a different project. The task gets a new number in the target project. Requires access to both source and target projects.",
    "input_schema": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string",
          "description": "Task code, e.g. \"ORB-73\"."
        },
        "target_project_code": {
          "type": "string",
          "description": "Target project code, e.g. \"HELM\"."
        }
      },
      "required": [
        "code",
        "target_project_code"
      ]
    }
  },
  {
    "name": "create_project",
    "description": "[Confidence: well-tested] Create a new project. Requires a name. The code is optional and will be auto-generated from the name if omitted. If provided, it must be unique, uppercase, alphanumeric (e.g. WORK, SIDE, TRAVEL).",
    "input_schema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Project name (e.g. \"Work\", \"Side Projects\")."
        },
        "code": {
          "type": "string",
          "description": "Optional short uppercase code (e.g. WORK, SIDE). If provided, it must be unique."
        },
        "description": {
          "type": "string",
          "description": "Optional project description."
        }
      },
      "required": [
        "name"
      ]
    }
  },
  {
    "name": "update_project",
    "description": "[Confidence: new] Update a project's name, description, or code. Users can only update their own projects. Use when the user says 'rename project X', 'change the description of X', etc.",
    "input_schema": {
      "type": "object",
      "properties": {
        "project_code": {
          "type": "string",
          "description": "Current project code to identify the project."
        },
        "new_name": {
          "type": "string",
          "description": "New project name."
        },
        "new_code": {
          "type": "string",
          "description": "New project code. Must be unique, uppercase, alphanumeric."
        },
        "new_description": {
          "type": "string",
          "description": "New project description. Pass empty string to clear."
        }
      },
      "required": [
        "project_code"
      ]
    }
  },
  {
    "name": "delete_project",
    "description": "[Confidence: new] Permanently delete a project and all its todos. IRREVERSIBLE. Users can only delete their own projects. MANDATORY: Before calling this tool, you MUST ask the user to confirm by saying exactly which project will be deleted and that all its todos will be lost. Only proceed after the user explicitly confirms (e.g. \"yes, delete it\"). Never delete without confirmation.",
    "input_schema": {
      "type": "object",
      "properties": {
        "project_code": {
          "type": "string",
          "description": "Project code to delete (e.g. \"WORK\")."
        },
        "confirmed": {
          "type": "boolean",
          "description": "Must be true. The AI sets this after receiving explicit user confirmation."
        }
      },
      "required": [
        "project_code",
        "confirmed"
      ]
    }
  },
  {
    "name": "set_dormancy",
    "description": "[Confidence: well-tested] Put a project to sleep (dormant) or wake it up. Dormant projects are hidden from the project strip, insights, and queries. Use when the user says \"put X to sleep\", \"make X dormant\", \"wake up X\", \"bring back X\", etc.",
    "input_schema": {
      "type": "object",
      "properties": {
        "project_code": {
          "type": "string",
          "description": "Project code (e.g. CAN26, HELM)."
        },
        "dormant": {
          "type": "boolean",
          "description": "true to put to sleep, false to wake up."
        }
      },
      "required": [
        "project_code",
        "dormant"
      ]
    }
  },
  {
    "name": "query_db",
    "description": "[Confidence: new] Execute a read-only database query via Supabase query builder. Use for questions that query_todos cannot answer: filtering by URLs, dates, groups, categories, joins, counts, or cross-table lookups. Returns raw rows up to 200. Always prefer query_todos for simple task lookups by code/status/priority.",
    "input_schema": {
      "type": "object",
      "properties": {
        "table": {
          "type": "string",
          "enum": [
            "todos",
            "projects",
            "knowledge_repo",
            "audit_log",
            "statuses",
            "priorities",
            "categories",
            "groups"
          ],
          "description": "Table to query."
        },
        "select": {
          "type": "string",
          "description": "Comma-separated columns or Supabase select syntax (e.g. '*, projects(code, name)'). Default: *"
        },
        "filters": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "column": {
                "type": "string",
                "description": "Column name to filter on."
              },
              "op": {
                "type": "string",
                "enum": [
                  "eq",
                  "neq",
                  "gt",
                  "gte",
                  "lt",
                  "lte",
                  "like",
                  "ilike",
                  "is",
                  "in",
                  "contains",
                  "overlaps",
                  "not.is"
                ],
                "description": "Filter operator."
              },
              "value": {
                "description": "Filter value. Use null for is/not.is. Use array for in/contains/overlaps."
              }
            },
            "required": [
              "column",
              "op",
              "value"
            ]
          },
          "description": "Array of filter conditions (AND'd together)."
        },
        "or_filter": {
          "type": "string",
          "description": "Supabase OR filter string, e.g. 'status.eq.open,status.eq.in progress'. Use sparingly."
        },
        "order": {
          "type": "string",
          "description": "Column to order by. Prefix with - for descending (e.g. '-created_at')."
        },
        "limit": {
          "type": "integer",
          "description": "Max rows to return (default 50, max 200)."
        }
      },
      "required": [
        "table"
      ]
    }
  }
]

export const ORB_TOOL_LABELS: Record<string, string> = {
  create_todo: 'Creating task...',
  query_todos: 'Searching backlog...',
  update_todo: 'Updating task...',
  delete_todo: 'Deleting task...',
  move_todo: 'Moving task...',
  client_action: 'Navigating...',
  search_knowledge: 'Searching knowledge repository...',
  add_knowledge: 'Saving to knowledge repository...',
  query_audit_trail: 'Checking history...',
  create_project: 'Creating project...',
  update_project: 'Updating project...',
  delete_project: 'Deleting project...',
  set_dormancy: 'Updating project...',
  create_ticket: 'Noting observation...',
  query_db: 'Querying database...',
}
