import { createHash } from 'node:crypto'
import { createClient } from '@/lib/supabase/server'
import { DB_SCHEMA } from '@/lib/db-schema'
import { classifyProviderFailure, notifyOrbIncident } from '@/lib/orb-model/incidents'

export const runtime = 'nodejs'

const REALTIME_MODEL = process.env.OPENAI_REALTIME_MODEL || 'gpt-realtime-2.1'

export async function POST(request: Request) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return Response.json({ error: 'Not authenticated' }, { status: 401 })
  if (!process.env.OPENAI_API_KEY) return Response.json({ error: 'OPENAI_API_KEY not configured' }, { status: 503 })

  const sdp = await request.text()
  if (!sdp || sdp.length > 100_000) return Response.json({ error: 'Invalid SDP offer' }, { status: 400 })
  const session = {
    type: 'realtime',
    model: REALTIME_MODEL,
    include: ['item.input_audio_transcription.logprobs'],
    instructions: [
      'You are Orb in an isolated development voice architecture test.',
      'Be conversational and concise. Never invent counts, task facts, identifiers, ownership, or mutation results.',
      'For factual or next-step questions, call the matching fact tool before speaking. Use get_project_directory for the count or names of projects the user owns, get_todo_details for one todo name or code, and list_todos when the user asks which tasks match. A task request that names any project is always named_project scope. Use all_owned only when the user explicitly asks across all projects, all of their projects, or overall. Never widen an omitted or uncertain project scope to all projects.',
      'For todo creation, call propose_create_todo. For any todo update, delete, or move, call the matching proposal tool directly with the todo name or code and any project name the user supplied. Preserve the user’s complete title phrase in todo_reference instead of shortening it to topic keywords. The server resolves exactly one current database row or rejects ambiguity; do not require the user to know a task code and do not perform a separate detail read first.',
      'Todo updates may change title, priority, or a non-closed status. Priority values are 1=urgent, 2=high, 3=normal, and 4=low. Translate those natural priority labels directly; never ask the user to supply the number after they used a known label.',
      'To close or complete a todo, call propose_close_todo with the todo reference and the user’s resolution_notes describing what was done. Closing always saves the resolution notes and writes a knowledge entry, so if the user has not said what was done, ask for a brief resolution before proposing. Never use propose_update_todo to set a closed status.',
      'For project creation, renaming, description changes, or deletion, call the matching project proposal tool directly. Project names are the user-facing identifier; project codes are immutable and generated by the server. Project deletion is permanent and also deletes every todo in that project, so say that plainly.',
      'Use search_knowledge for Knowledge Repository reads. Use topic_query for discovery and title for one named entry. Use propose_add_knowledge to save a new insight and propose_update_knowledge to correct an existing entry. There is deliberately no knowledge delete tool.',
      'Use query_tickets for reporter-facing ticket status and lists; it is admin-only and read-only. Use query_audit for change history. Use query_repository for implementation/source questions when the user’s role permits it. Never substitute tickets for todos or claim a read-only ticket mutation exists.',
      'Use client_action for verified navigation, project switching, saved voice selection, and exiting voice mode. Use get_preferences and set_preference for explicit Orb settings. Use recall_memories before save_memory to avoid duplicates. propose_adaptation creates a pending email-approved proposal, never an active rule. Use create_ticket for bugs or workflow friction, query_capabilities for the current contract, and send_to_developer only when the user explicitly asks to relay something.',
      'Never say a mutation happened until a proposal or confirmation tool returns a database receipt. A proposal without a receipt is still pending.',
      'The server—not you—decides whether the user granted permission in the requesting utterance or explicitly approved a pending proposal. Never call confirm_todo_mutation to resolve a complaint, discussion, or reminder about earlier permission.',
      'Never describe, quote, or guess which exact words the server accepts as approval; you do not know that grammar and stating it misleads the user. If a confirmation is rejected, briefly restate the pending change and ask the user to approve it in their own words.',
      'A proposal is not a completed action. Ask for confirmation exactly once.',
      'When a tool returns spokenText, say that exact factual core without changing any number, identifier, title, project, or completion state.',
      'Do not offer surveys or unrelated follow-up work.',
      // query_db needs real column names, or it fails at the database layer
      // (guessed columns error out — the model has no other way to know them).
      // Kept as its own block, appended after the space-joined prose above, so
      // the schema's table/column line breaks reach the model intact.
    ].join(' ') + '\n\nDATABASE SCHEMA (for query_db, allowlisted tables/columns only):\n' + DB_SCHEMA,
    audio: {
      input: {
        noise_reduction: { type: 'far_field' },
        transcription: { model: 'gpt-4o-mini-transcribe' },
        turn_detection: {
          type: 'server_vad',
          // Raised from 0.65 (Stan, 2026-07-17): on speakerphone, Orb's own
          // voice echoes back into the mic and the provider VAD misread that
          // echo as the user interrupting, cutting Orb off mid-sentence.
          // Confirmed acoustic (clean with headphones/AirPods) rather than an
          // over-eager VAD, so the fix is a stricter volume gate rather than
          // gating interruption through Silero. Real speech remains well above
          // this threshold; re-tune from live speakerphone testing.
          threshold: 0.8,
          prefix_padding_ms: 300,
          silence_duration_ms: 450,
          // The provider truncates its own audio the instant the user speaks
          // over it (interrupt_response) — so the client never sends
          // response.cancel, which is what removed the fatal cancel/create
          // races. But it does NOT auto-create the response: create_response
          // is false because auto-creating at commit time (before the input
          // item is fully in context) produced empty responses. The client
          // creates the response once the transcript is ready instead. The VAD
          // `threshold` above is the volume gate for what counts as speech.
          create_response: false,
          interrupt_response: true,
        },
      },
      output: { voice: 'marin' },
    },
    tools: [
      {
        type: 'function',
        name: 'get_task_count',
        description: 'Get an exact live task count. Choose named_project whenever the user names a project; choose all_owned only for an explicit across-all-projects request. “Open” means status=open only; “active” means open plus in progress; “parked” means deferred plus on hold. The server rejects missing or inconsistent scope instead of widening it.',
        parameters: {
          type: 'object',
          properties: {
            project_scope: { type: 'string', enum: ['named_project', 'all_owned'], description: 'named_project if any project was named; all_owned only if the user explicitly requested a cross-project total.' },
            project_name: { type: 'string', description: 'User-facing project name. Required when project_scope is named_project; omit for all_owned.' },
            status_scope: { type: 'string', enum: ['open', 'active', 'parked', 'all'] },
          },
          required: ['project_scope', 'status_scope'],
          additionalProperties: false,
        },
      },
      { type: 'function', name: 'get_project_directory', description: 'Get the exact live count and names of current, non-dormant projects owned by the user.', parameters: { type: 'object', properties: {}, additionalProperties: false } },
      { type: 'function', name: 'query_projects', description: 'Read richer project facts such as description, owner id, dormant state, and partial-name resolution.', parameters: { type: 'object', properties: { name: { type: 'string' }, include_dormant: { type: 'boolean' }, max_results: { type: 'integer', minimum: 1, maximum: 100 } }, additionalProperties: false } },
      { type: 'function', name: 'query_db', description: 'Bounded read-only structural query using an allowlisted table, plain columns, and declarative filters. Never raw SQL.', parameters: { type: 'object', properties: { table: { type: 'string', enum: ['todos', 'projects', 'knowledge_repo', 'audit_log', 'statuses', 'priorities', 'categories', 'groups', 'tickets'] }, select: { type: 'string', description: 'Comma-separated plain column names only.' }, filters: { type: 'array', items: { type: 'object', properties: { column: { type: 'string' }, op: { type: 'string', enum: ['eq', 'neq', 'gt', 'gte', 'lt', 'lte', 'like', 'ilike', 'is', 'in', 'contains', 'overlaps', 'not.is'] }, value: {} }, required: ['column', 'op', 'value'], additionalProperties: false } }, order: { type: 'string', description: 'Column, or -column for descending.' }, limit: { type: 'integer', minimum: 1, maximum: 200 } }, required: ['table'], additionalProperties: false } },
      { type: 'function', name: 'get_todo_details', description: 'Read one live todo by its natural title or code. Include the project name when the user supplies it. The server rejects ambiguous matches.', parameters: { type: 'object', properties: { todo_reference: { type: 'string', description: 'Todo title or exact code.' }, project_name: { type: 'string', description: 'Optional user-facing project name.' } }, required: ['todo_reference'], additionalProperties: false } },
      {
        type: 'function', name: 'list_todos',
        description: 'List matching live todos. Choose named_project whenever the user names a project; choose all_owned only for an explicit cross-project request. The server rejects missing or inconsistent project scope.',
        parameters: {
          type: 'object',
          properties: {
            project_scope: { type: 'string', enum: ['named_project', 'all_owned'] },
            project_name: { type: 'string', description: 'Required for named_project; omit for all_owned.' },
            status_scope: { type: 'string', enum: ['open', 'active', 'parked', 'all'] },
            text_match: { type: 'string', description: 'Optional title text filter.' },
            max_results: { type: 'integer', minimum: 1, maximum: 10 },
          },
          required: ['project_scope', 'status_scope'],
          additionalProperties: false,
        },
      },
      { type: 'function', name: 'get_next_step', description: 'Get one recommended next task from a live owned-project database snapshot.', parameters: { type: 'object', properties: {}, additionalProperties: false } },
      { type: 'function', name: 'propose_create_todo', description: 'Prepare, but do not execute, one todo creation for confirmation. Include project_name whenever the user names a project; otherwise the current project is used.', parameters: { type: 'object', properties: { title: { type: 'string' }, project_name: { type: 'string' } }, required: ['title'], additionalProperties: false } },
      {
        type: 'function', name: 'propose_update_todo',
        description: 'Resolve and prepare an update from a natural todo title or code. Include the project name when supplied. At least one new value is required. Closed status is intentionally unavailable.',
        parameters: {
          type: 'object', properties: {
            todo_reference: { type: 'string', description: 'The user’s complete todo title phrase or exact code; do not shorten it to topic keywords.' },
            project_name: { type: 'string' },
            new_title: { type: 'string' },
            new_status: { type: 'string', enum: ['open', 'in progress', 'deferred', 'on hold'] },
            new_priority: { type: 'integer', minimum: 1, maximum: 4, description: '1=urgent, 2=high, 3=normal, 4=low.' },
          }, required: ['todo_reference'], additionalProperties: false,
        },
      },
      { type: 'function', name: 'propose_delete_todo', description: 'Resolve and prepare deletion from a natural todo title or code. Include the project name when supplied.', parameters: { type: 'object', properties: { todo_reference: { type: 'string' }, project_name: { type: 'string' } }, required: ['todo_reference'], additionalProperties: false } },
      { type: 'function', name: 'propose_move_todo', description: 'Resolve and prepare moving a natural todo title or code to a project named by the user.', parameters: { type: 'object', properties: { todo_reference: { type: 'string' }, project_name: { type: 'string', description: 'Current/source project name when supplied.' }, target_project_name: { type: 'string' } }, required: ['todo_reference', 'target_project_name'], additionalProperties: false } },
      {
        type: 'function', name: 'propose_close_todo',
        description: 'Resolve and prepare closing (completing) a todo from a natural title or code. Closing always saves resolution_notes and writes a knowledge entry, so resolution_notes is required — ask the user what was done if they have not said. Include the project name when supplied.',
        parameters: {
          type: 'object', properties: {
            todo_reference: { type: 'string', description: 'The user’s complete todo title phrase or exact code.' },
            project_name: { type: 'string', description: 'Optional user-facing project name.' },
            resolution_notes: { type: 'string', description: 'What was actually done to resolve the todo, in the user’s words.' },
            knowledge_title: { type: 'string', description: 'Optional short title for the knowledge entry; defaults to the todo code and title.' },
            knowledge_content: { type: 'string', description: 'Optional distilled lesson for the knowledge entry; defaults to the resolution notes.' },
          }, required: ['todo_reference', 'resolution_notes'], additionalProperties: false,
        },
      },
      { type: 'function', name: 'propose_create_project', description: 'Prepare creation of a project using the exact user-provided name. The server generates the immutable project code.', parameters: { type: 'object', properties: { name: { type: 'string' }, description: { type: 'string' } }, required: ['name'], additionalProperties: false } },
      { type: 'function', name: 'propose_update_project', description: 'Resolve a project by its current name and prepare a rename and/or description change. Project codes cannot be changed.', parameters: { type: 'object', properties: { name: { type: 'string', description: 'Current project name.' }, new_name: { type: 'string' }, new_description: { type: 'string', description: 'New description; empty string clears it.' } }, required: ['name'], additionalProperties: false } },
      { type: 'function', name: 'propose_delete_project', description: 'Resolve and prepare permanent deletion of a project and every todo it contains. This is irreversible.', parameters: { type: 'object', properties: { name: { type: 'string' } }, required: ['name'], additionalProperties: false } },
      { type: 'function', name: 'search_knowledge', description: 'Read the Knowledge Repository by topic or by one title reference. Provide topic_query or title, not both.', parameters: { type: 'object', properties: { topic_query: { type: 'string' }, title: { type: 'string' }, project_name: { type: 'string' }, max_results: { type: 'integer', minimum: 1, maximum: 10 } }, additionalProperties: false } },
      { type: 'function', name: 'propose_add_knowledge', description: 'Prepare saving a new attributed Knowledge Repository entry in the current or named project.', parameters: { type: 'object', properties: { title: { type: 'string' }, content: { type: 'string' }, project_name: { type: 'string' }, tags: { type: 'array', items: { type: 'string' } } }, required: ['title', 'content'], additionalProperties: false } },
      { type: 'function', name: 'propose_update_knowledge', description: 'Resolve one existing knowledge entry by title and prepare a title and/or content correction. There is no delete tool.', parameters: { type: 'object', properties: { title: { type: 'string', description: 'Existing title reference.' }, new_title: { type: 'string' }, new_content: { type: 'string' } }, required: ['title'], additionalProperties: false } },
      { type: 'function', name: 'query_tickets', description: 'Admin-only, read-only ticket lookup. Use code for one full ticket or filters for a compact list. Tickets cannot be updated or deleted by voice.', parameters: { type: 'object', properties: { code: { type: 'string' }, status: { type: 'string' }, scope: { type: 'string', enum: ['active', 'all'] }, type: { type: 'string', enum: ['bug', 'suggestion', 'capability_gap', 'workflow_friction'] }, search: { type: 'string' }, max_results: { type: 'integer', minimum: 1, maximum: 50 } }, additionalProperties: false } },
      { type: 'function', name: 'query_audit', description: 'Read audit history by todo code, table, action, and/or date.', parameters: { type: 'object', properties: { code: { type: 'string' }, table_name: { type: 'string' }, action: { type: 'string' }, since: { type: 'string' }, max_results: { type: 'integer', minimum: 1, maximum: 50 } }, additionalProperties: false } },
      { type: 'function', name: 'query_repository', description: 'Inspect allowlisted local or production source. Role-gated to Admin, Super Admin, and Developer.', parameters: { type: 'object', properties: { operation: { type: 'string', enum: ['list', 'search', 'read'] }, source: { type: 'string', enum: ['local', 'production'] }, path: { type: 'string' }, query: { type: 'string' }, start_line: { type: 'integer' }, end_line: { type: 'integer' }, max_results: { type: 'integer', minimum: 1, maximum: 100 } }, required: ['operation'], additionalProperties: false } },
      { type: 'function', name: 'client_action', description: 'Navigate or change verified client state.', parameters: { type: 'object', properties: { action: { type: 'string', enum: ['switch_project', 'open_settings', 'open_help', 'set_voice', 'exit_voice'] }, target: { type: 'string', description: 'Project name or voice name when required.' } }, required: ['action'], additionalProperties: false } },
      { type: 'function', name: 'set_project_dormancy', description: 'Put a named project to sleep or wake it. The server resolves the name and verifies access.', parameters: { type: 'object', properties: { name: { type: 'string' }, dormant: { type: 'boolean' } }, required: ['name', 'dormant'], additionalProperties: false } },
      { type: 'function', name: 'get_preferences', description: 'Read saved Orb preferences and available keys.', parameters: { type: 'object', properties: {}, additionalProperties: false } },
      { type: 'function', name: 'set_preference', description: 'Save one explicit Orb preference. The server validates the value.', parameters: { type: 'object', properties: { key: { type: 'string', enum: ['guidance_level', 'verbosity', 'openness', 'memory_level', 'scope_reminders', 'mutation_approval', 'survey_completed', 'survey_stage'] }, value: { type: 'string' } }, required: ['key', 'value'], additionalProperties: false } },
      { type: 'function', name: 'recall_memories', description: 'Read active cross-session memories, optionally filtered.', parameters: { type: 'object', properties: { category: { type: 'string', enum: ['pattern', 'rhythm', 'preference', 'emotional', 'milestone'] }, query: { type: 'string' }, limit: { type: 'integer', minimum: 1, maximum: 30 } }, additionalProperties: false } },
      { type: 'function', name: 'save_memory', description: 'Save an autonomous repeated pattern or an offered memory the user agreed to preserve. Recall first to avoid duplicates.', parameters: { type: 'object', properties: { track: { type: 'string', enum: ['autonomous', 'offered'] }, category: { type: 'string', enum: ['pattern', 'rhythm', 'preference', 'emotional', 'milestone'] }, content: { type: 'string' }, context: { type: 'string' } }, required: ['track', 'category', 'content'], additionalProperties: false } },
      { type: 'function', name: 'propose_adaptation', description: 'Create a pending behavioral adaptation and email it for user approval. It does not activate the rule.', parameters: { type: 'object', properties: { title: { type: 'string' }, rule: { type: 'string' }, rationale: { type: 'string' }, category: { type: 'string', enum: ['communication', 'observation', 'coaching', 'workflow'] } }, required: ['title', 'rule', 'rationale', 'category'], additionalProperties: false } },
      { type: 'function', name: 'create_ticket', description: 'Log a bug, suggestion, capability gap, or workflow friction in the reporter-facing ticket queue.', parameters: { type: 'object', properties: { type: { type: 'string', enum: ['bug', 'suggestion', 'capability_gap', 'workflow_friction'] }, summary: { type: 'string' }, detail: { type: 'string' } }, required: ['type', 'summary'], additionalProperties: false } },
      { type: 'function', name: 'query_capabilities', description: 'Load the current Orb capability and constraint contract.', parameters: { type: 'object', properties: { section: { type: 'string' } }, additionalProperties: false } },
      { type: 'function', name: 'send_to_developer', description: 'Send an explicit actionable message through the existing developer channel.', parameters: { type: 'object', properties: { content: { type: 'string' }, target_tool: { type: 'string' } }, required: ['content'], additionalProperties: false } },
      { type: 'function', name: 'confirm_todo_mutation', description: 'Execute exactly one previously proposed todo, project, or Knowledge Repository mutation after the user explicitly confirms it.', parameters: { type: 'object', properties: { proposal_token: { type: 'string' } }, required: ['proposal_token'], additionalProperties: false } },
    ],
  }

  const form = new FormData()
  form.set('sdp', sdp)
  form.set('session', JSON.stringify(session))
  const response = await fetch('https://api.openai.com/v1/realtime/calls', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
      'OpenAI-Safety-Identifier': createHash('sha256').update(user.id).digest('hex'),
    },
    body: form,
  })
  const body = await response.text()
  if (!response.ok) {
    console.error('[orb-realtime] session creation failed:', response.status, body.slice(0, 500))
    const parsedError = (() => { try { return JSON.parse(body) } catch { return { message: body.slice(0, 500) } } })()
    const failure = classifyProviderFailure(parsedError, 'openai', 'voice')
    notifyOrbIncident({
      summary: failure.summary,
      provider: 'openai',
      role: 'voice',
      reason: failure.reason,
      detail: { error: failure.message, type: failure.type, status: response.status },
      consoleUrl: failure.consoleUrl,
    }).catch(error => console.error('[orb-realtime] Incident notification failed:', error))
    return Response.json({ error: failure.userMessage }, { status: 502 })
  }
  return new Response(body, { headers: { 'Content-Type': 'application/sdp' } })
}
